// <auto-generated />
using asp_ecommerce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace asp_ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171101195313_refactored")]
    partial class refactored
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("asp_ecommerce.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FName");

                    b.Property<string>("LName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("asp_ecommerce.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserEmail");

                    b.Property<int>("ApplicationUserId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("UserId");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("asp_ecommerce.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("CustomerId");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("asp_ecommerce.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrderId");

                    b.Property<DateTime>("Ordered_date");

                    b.Property<int>("ProductId");

                    b.Property<int>("QtyOrdered");

                    b.HasKey("OrderProductId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("asp_ecommerce.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserName");

                    b.Property<DateTime>("Created_date_by_seller");

                    b.Property<string>("Desc");

                    b.Property<string>("Name");

                    b.Property<int>("Qty");

                    b.Property<string>("Url");

                    b.Property<string>("UserId");

                    b.HasKey("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                //{
                //    b.Property<string>("Id")
                //        .ValueGeneratedOnAdd();

                //    b.Property<string>("ConcurrencyStamp")
                //        .IsConcurrencyToken();

                //    b.Property<string>("Name")
                //        .HasMaxLength(256);

                //    b.Property<string>("NormalizedName")
                //        .HasMaxLength(256);

                //    b.HasKey("Id");

                //    b.HasIndex("NormalizedName")
                //        .IsUnique()
                //        .HasName("RoleNameIndex");

                //    b.ToTable("AspNetRoles");
                //});

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                //{
                //    b.Property<int>("Id")
                //        .ValueGeneratedOnAdd();

                //    b.Property<string>("ClaimType");

                //    b.Property<string>("ClaimValue");

                //    b.Property<string>("RoleId")
                //        .IsRequired();

                //    b.HasKey("Id");

                //    b.HasIndex("RoleId");

                //    b.ToTable("AspNetRoleClaims");
                //});

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                //{
                //    b.Property<int>("Id")
                //        .ValueGeneratedOnAdd();

                //    b.Property<string>("ClaimType");

                //    b.Property<string>("ClaimValue");

                //    b.Property<string>("UserId")
                //        .IsRequired();

                //    b.HasKey("Id");

                //    b.HasIndex("UserId");

                //    b.ToTable("AspNetUserClaims");
                //});

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                //{
                //    b.Property<string>("LoginProvider");

                //    b.Property<string>("ProviderKey");

                //    b.Property<string>("ProviderDisplayName");

                //    b.Property<string>("UserId")
                //        .IsRequired();

                //    b.HasKey("LoginProvider", "ProviderKey");

                //    b.HasIndex("UserId");

                //    b.ToTable("AspNetUserLogins");
                //});

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            //    {
            //        b.Property<string>("UserId");

            //        b.Property<string>("RoleId");

            //        b.HasKey("UserId", "RoleId");

            //        b.HasIndex("RoleId");

            //        b.ToTable("AspNetUserRoles");
            //    });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                //{
                    //b.Property<string>("UserId");

                    //b.Property<string>("LoginProvider");

                    //b.Property<string>("Name");

                //    b.Property<string>("Value");

                //    b.HasKey("UserId", "LoginProvider", "Name");

                //    b.ToTable("AspNetUserTokens");
                //});

            modelBuilder.Entity("asp_ecommerce.Models.Customer", b =>
                {
                    b.HasOne("asp_ecommerce.Models.ApplicationUser", "User")
                        .WithOne("Customer")
                        .HasForeignKey("asp_ecommerce.Models.Customer", "UserId");
                });

            modelBuilder.Entity("asp_ecommerce.Models.Order", b =>
                {
                    b.HasOne("asp_ecommerce.Models.Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("asp_ecommerce.Models.OrderProduct", b =>
                {
                    b.HasOne("asp_ecommerce.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("asp_ecommerce.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("asp_ecommerce.Models.Product", b =>
                {
                    b.HasOne("asp_ecommerce.Models.ApplicationUser", "User")
                        .WithMany("ProductsToSell")
                        .HasForeignKey("UserId");
                });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            //    {
            //        b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
            //            .WithMany()
            //            .HasForeignKey("RoleId")
            //            .OnDelete(DeleteBehavior.Cascade);
            //    });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            //    {
            //        b.HasOne("asp_ecommerce.Models.ApplicationUser")
            //            .WithMany()
            //            .HasForeignKey("UserId")
            //            .OnDelete(DeleteBehavior.Cascade);
            //    });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                //{
                //    b.HasOne("asp_ecommerce.Models.ApplicationUser")
                //        .WithMany()
                //        .HasForeignKey("UserId")
                //        .OnDelete(DeleteBehavior.Cascade);
                //});

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            //    {
            //        b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
            //            .WithMany()
            //            .HasForeignKey("RoleId")
            //            .OnDelete(DeleteBehavior.Cascade);

            //        b.HasOne("asp_ecommerce.Models.ApplicationUser")
            //            .WithMany()
            //            .HasForeignKey("UserId")
            //            .OnDelete(DeleteBehavior.Cascade);
            //    });

            //modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                //{
                //    b.HasOne("asp_ecommerce.Models.ApplicationUser")
                //        .WithMany()
                //        .HasForeignKey("UserId")
                //        .OnDelete(DeleteBehavior.Cascade);
                //});
#pragma warning restore 612, 618
        }
    }
}
